[package]
name = "rsa_demo"
version = "0.1.0"
authors = ["wuhaurou <wobusbz2019@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsa = "0.4.0"
base64 = "0.13.0"
rust-crypto = "0.2.36"